defaults: &defaults
  adapter: postgresql
  pool: 5
  timeout: 5000

test:
  <<: *defaults
  database: rhymeio-test
  host: 127.0.0.1
  min_messages: WARNING

development:
  <<: *defaults
  database: rhymeio-development
  host: 127.0.0.1

production:
  <<: *defaults
  pool: 12
  database: rhymeio-production
